### ISSUE TITLE
Rename `Error` module.

### ISSUE THREAD

**Issue by jetaggart** [abadi199/dateparser#7]
Would it be possible to rename the `Error` module and nest it under `DateParser.Error`? This is a very general module name and easily causes naming conflicts between code. Unfortunately, it looks like there's no way around this currently:

https://github.com/elm-lang/elm-compiler/issues/1625

**Comment by abadi199** [comment]
Absolutely, I think that's a great idea. I don't think I will have to do
that, so if you want to make a pull request, I will be happy to merge and
publish that.
